# Generated by Django 3.1.7 on 2021-05-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='flashcard_definition',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='flashcard_term',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
